name: Deploy to Strato

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout Code
        uses: actions/checkout@v4

      - name: 🐘 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer

      - name: 📦 Install Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: 🚀 Incremental Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          # Lade in das Root-Verzeichnis deines FTP-Users
          server-dir: /
          # Verhindert, dass das State-File von Strato gelöscht wird
          state-name: .ftp-deploy-sync-state.json